<?php
/**
 * @package Localization
 * @subpackage Translator
 */

declare(strict_types=1);

namespace AppLocalize\Localization\Translator;

use AppLocalize\Localization\Locales\LocaleInterface;
use AppUtils\FileHelper;

/**
 * Utility used to write localized strings to an ini file.
 *
 * @package Localization
 * @subpackage Translator
 * @author Sebastian Mordziol <s.mordziol@mistralys.eu>
 */
class LocalizationWriter
{
   /**
    * @var array<string,string>
    */
    private array $hashes = array();

    private bool $editable = false;
    private LocaleInterface $locale;
    private string $fileType;
    private string $filePath;
    private string $hashFilePath;
    
    public function __construct(LocaleInterface $locale, string $fileType, string $filePath)
    {
        $this->locale = $locale;
        $this->fileType = $fileType;
        $this->filePath = $filePath;
        $this->hashFilePath = $filePath.'.hash';
    }
    
    public function makeEditable() : LocalizationWriter
    {
        $this->editable = true;
        
        return $this;
    }
    
    public function addHash(string $hash, string $text) : LocalizationWriter
    {
        $this->hashes[$hash] = $text;
        
        return $this;
    }
    
    public function writeFile() : void
    {
        $content = 
        $this->renderHead().
        $this->renderHashes();
        
        FileHelper::saveFile($this->filePath, $content);
        FileHelper::saveFile($this->hashFilePath, hash('crc32c', $content));
    }
    
    private function renderHashes() : string
    {
        $hashes = $this->compileHashes();
        $lines = array();
        
        foreach($hashes as $entry)
        {
            $lines[] = sprintf(
                '%s= "%s"',
                $entry['hash'],
                str_replace('"', '\"', $entry['text'])
            );
        }
        
        $lines[] = '';
        
        return implode(PHP_EOL, $lines);
    }
    
    private function renderHead() : string
    {
        $title = strtoupper($this->fileType).' TRANSLATION FILE FOR ' . strtoupper($this->locale->getLabel());
        
        $lines = array();
        
        $lines[] = '; -------------------------------------------------------';
        $lines[] = '; '. $title;
        $lines[] = '; -------------------------------------------------------';
        $lines[] = '; ';
        
        if($this->editable) 
        {
            $lines[] = '; You may edit text directly in this file under the following conditions:';
            $lines[] = '; ';
            $lines[] = '; 1) Do not to modify the keys (left hand side of the = sign)';
            $lines[] = '; 2) Save the file as UTF-8 without BOM';
        } 
        else 
        {
            $lines[] = '; Do NOT edit this file directly! It depends on the main translation file';
            $lines[] = '; and any changes will be lost. Edit the main file instead.';
        }
        
        $lines[] = PHP_EOL;
        
        return implode(PHP_EOL, $lines);
    }

    /**
     * Collects and sorts the strings to ensure they always
     * appear in the same order: First by text, and same strings
     * by their hashes. This is important for strings that have
     * the same translation to avoid them changing order between sorts.
     *
     * @return array<int, array{hash:string, text:string}>
     */
    private function compileHashes() : array
    {
        $hashes = array();
        
        foreach($this->hashes as $hash => $text)
        {
            $hashes[] = array(
                'hash' => $hash,
                'text' => $text
            );
        }
        
        usort($hashes, static function(array $a, array $b) : int {
            $result = strnatcasecmp($a['text'], $b['text']);

            if($result !== 0)
            {
                return $result;
            }

            return strnatcmp($a['hash'], $b['hash']);
        });
        
        return $hashes;
    }
}
